branches:
  only:
  - master
language: node_js
node_js:
  - "4.1"
install:
  - npm install -g bower
  - npm install
  - bower install
before_script:
  - git remote set-url origin "https://${GH_TOKEN}@github.com/DaMitchell/easeljs-resizable.git"
  - git config --global user.email "danmitchellster@gmail.com"
  - git config --global user.name "Travis-CI"
script:
  - gulp deploy
env:
  global:
  - secure: "rYBxf8/odOuoeCvv/9myQWuEFISBbjnxrUwXuFnHQq9bYKGFtGBMaml+8j/nXGj02RcxRIHcB2oiSUd3DZCnFxXhsy0OJyvndxYQtd4xfhAdeaEQb/l9DPkB6nLJlrfXHgpFPHZEC/1SccSW4l5u1W7UAL6pXW3AD8vz+qVpZldexlNrFqrDtl5tI3UAuwpN4Qx7BmAooZ7PRWAwNGZXEWQQ5neHpuMf9dA3N6hFhZ35N+xOUpUuqa3uLKUiTDGiNj1h79jFX+lFd5t+NJf8arGiJyD0dHxaNTWXTFcoe5uasIWnPhibPJPHqz+N9hfVnI30/wsl9yaLH+d2y0h/xAjIS8vr0A/eJpzyZ4qmiPJp68Gr8+sTQF1+etYT9+C60AFjen+G1bjSX06wqy0D+7LdNIR3xxlBYQ9omDO1j8LfSVRXj/i0nbS3BFt+tYBssLEVhqcL7QG5vqHZoPJ5bbVG9BqPJMZa9FPy4ro/mBf1bTBvxkmUIBibp+0t7taOiE/I5+I32F59o8l8AvwHsqiMzToDcMhRncvzD4fN1ly0uScpLyMP68U47lwZo0OrnZ9i/MeA28iIQUPGkyszcUSUZqAxwz7k42z/3FrdZXWYVIa7zS6PGo60T9SmlAoLLwipEakAmGRDlFKTL7JD7ZYlsfDOS0O6LEPFyaKKmoM="
